version: '3'
services:
  vertica:
    image: vertica/vertica-ce:12.0.4-0
    environment:
      - DATABASE_PASSWORD=foo123
    ports:
      - "5433:5433"
  checks:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - vertica_host=vertica
    depends_on:
      - vertica
